### PR TITLE
update heapless and hash32

### PR DESCRIPTION
**Pull request by tarfu**

### CODE REVIEW

**Comment by MathiasKoch** [comment]
Thanks! 
Could you make the CI happy on the tests & linting?

**Comment by tarfu** [comment]
I'm not really sure what it is about the linker errors in the Test.
Using it in, for example, ublox-cellular-rs it is just fine building.

**Comment by tarfu** [comment]
The commit fixes the linking issue but not the tests itself which fail. But they don't seem to be related to the changes

**Comment by MathiasKoch** [comment]
Fair enough. Should we maybe change the CI to run that as tests instead?

**Comment by tarfu** [comment]
Yes, I think that's a sensible solution.

**Comment by MathiasKoch** [comment]
I don't understand why these tests are suddenly failing ...

**Comment by tarfu** [comment]
I tried to fix the tests on a logic level, but please take a look if they are still what they supposed to be.

**Comment by MathiasKoch** [comment]
Ahh, Yeah.. I now see that the issue was originally on me, as I never actually ran the tests on this WIP async branch. 

What you have done here seems super reasonable! Thanks!

I am sorry!

**Pull request merged**
